local hl = vim.api.nvim_set_hl
return {
    c_hl = function()
        hl(0, "@keyword.import", {link = "@keyword"})
        hl(0, "@keyword.modifier", {link = "@keyword"})
        hl(0, "@keyword.type", {link = "@keyword"})
        hl(0, "@keyword.repeat", {link = "@keyword"})
        hl(0, "@keyword.conditional", {link = "@keyword"})
        hl(0, "@keyword.directive.define", {link = "@keyword"})
        hl(0, "@keyword", {fg = "#ddc9c0", force = true})
        hl(0, "@type.builtin", {link = "@type"})
        hl(0, "@lsp.type.macro", {link = "@type"})
        hl(0, "@type.definition", {link = "@type"})
        hl(0, "@type", {fg = "#8ecae6", force = true})
        hl(0, "@lsp.typemod.macro.globalScope.c", {link = "@constant"})
        hl(0, "@number", {link = "@constant"})
        hl(0, "@constant.builtin", {link = "@constant"})
        hl(0, "@constant", {fg = "#ef8d67", force = true})
        hl(0, "@property", {link = "@variable"})
        hl(0, "@variable.parameter", {link = "@variable"})
        hl(0, "@variable", {fg = "#FFFFFF", force = true})
        hl(0, "@function.macro", {link = "@constant.macro"})
        hl(0, "@constant.macro", {fg = "#86e1fc", force = true})
        hl(0, "@function", {fg = "#a4c3b2", force = true})
        hl(0, "@string", {fg = "#c3e88d", force = true})
    end,
}
