local map  = vim.keymap.set
local del  = vim.keymap.del

map('t', '<Esc>', [[<C-\><C-n>]], {noremap=true})
map('n', '<C-p>', "\"+p", {noremap=true})
map('n', '<C-q>', "ZZ", {noremap=true})
del('n', 'j')
del('n', 'k')
map({'i', 'c', 't'}, "<C-backspace>", "<C-w>", {noremap=true})
map("n", "<leader>h", "<CMD>:lua require('nvim-highlight-colors').toggle()<CR>", {})
map("i", "<C-/>", "<C-o>:NeotermToggle<CR>", {})
map("t", "<C-/>", "<CMD>:NeotermToggle<CR>", {})
map("n", "<C-/>", "<CMD>:NeotermToggle<CR>", {})
map("i", "<C-_>", "<C-o>:NeotermToggle<CR>", {})
map("t", "<C-_>", "<CMD>:NeotermToggle<CR>", {})
map("n", "<C-_>", "<CMD>:NeotermToggle<CR>", {})
-- map("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
map("n", "<leader>a", "<C-z>", {})
map("n", "<A-k>", "<esc>k", { desc = "Move up" })
map("n", "<A-j>", "<esc>j", { desc = "Move down" })
map("i", "<A-k>", "<esc>gk", { desc = "Move up" })
map("i", "<A-j>", "<esc>gj", { desc = "Move down" })
map("v", "<A-k>", "<esc>gk", { desc = "Move up" })
map("v", "<A-j>", "<esc>gj", { desc = "Move down" })
